version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - /root/nginx/html:/usr/share/nginx/html
    - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  blog:
    image: blog:latest
    build: .
    ports:
    - 8081:8081
